### ISSUE TITLE
fence_chroma monitor action always return status 0

### ISSUE THREAD

**Issue by freishutz** [whamcloud/iml-agent#75]
According to [official documentation](https://clusterlabs.org/pacemaker/doc/crm_fencing.html) :

> **Monitoring the fencing devices**
> Just like any other resource, the stonith class agents also support the monitor operation. Given that we have often seen **monitor either not configured or configured in a wrong way**, we have decided to devote a section to the matter.
> Monitoring stonith resources, which is actually checking status of the corresponding fencing devices, is strongly recommended. So strongly, that we should consider a configuration without it invalid.

Good example of how it works could be taken from "fence-agents-scsi rpm for CentOS v7".

Due to issue [824](https://github.com/whamcloud/integrated-manager-for-lustre/issues/824) we could have a situation when we don't have fencing device or our fencing device is not ready and as a result fencing will not occur never.

**Comment by jgrund** [comment]
Ref of hardcoded no-op:

https://github.com/whamcloud/iml-agent/blob/430bb6bce7960391f3d4b895ab48e51d83f06795/chroma_agent/fence_chroma.py#L111-L117
